---
- name: Converge
  hosts: all
  pre_tasks:
    # https://www.jeffgeerling.com/blog/2020/resolving-fedora-dnf-error-no-such-file-or-directory-varlibdnfrpmdblockpid
    - name: Wait for systemd to complete initialization.          # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: "'running' in systemctl_status.stdout"
      retries: 30
      delay: 5
      # first line made Debian VMs fail, so I decided to filter for Fedora distribution
      # when: ansible_service_mgr == 'systemd'
      when: ansible_distribution == 'Fedora'
      changed_when: false

  roles:
    - role: ansible-rclone
