on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    matrix:
      scenario:
        - centos-7
        - debian-9
        - fedora-32
        - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: --scenario_name ${{ matrix.scenario }}
