---

name: Molecule

on:
  push:
    branches:
      - master
      - ci_*
  pull_request:
    branches:
      - master

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - travis
        distros:
          - centos7
          - centos8
          - debian10
          - debian9
          - fedora31
          - fedora32
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
        versions:
          - stable
          - beta
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Molecule
        uses: robertdebock/molecule-action@2.6.3
        env:
          MOLECULE_DISTRO: "${{ matrix.distros }}"
          rclone_version: "${{ matrix.versions }}"
        with:
          options: parallel
          scenario: ${{ matrix.scenario }}
